name: Nightly Release

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  create-tag:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Date Tag
        run: echo "TAG_NAME=nightly-$(date +'%m-%d-%Y')" >> $GITHUB_ENV

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}